
<weather>:

    orientation: "vertical"
    pos_hint: {'x':0.5, 'top':0.5}
    BoxLayout:
        pos: 1,1
        height: 100

        #size_hint: None,1
        TextInput:

            size_hint_x: 50
        Button:
            text: "Search"
            size_hint_x:25
            on_press: root.inputs()

        Button:
            text: "Current Location"
            size_hint_x:25
    ListView:
        pos:10,10
        item_strings: ['location 1', 'Location 2']